// <auto-generated />
using System;
using System.Collections.Generic;
using DBGuardAPI.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBGuardAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427231514_Latest")]
    partial class Latest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBGuardAPI.Data.Models.DatabaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DatabaseEngine")
                        .HasColumnType("integer")
                        .HasColumnName("database_engine");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_point");

                    b.Property<DateTimeOffset>("LastEditedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_date");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_database_connections");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_database_connections_created_by_user_id");

                    b.ToTable("database_connections", (string)null);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.Guard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountColumn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("count_column");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DatabaseConnectionId")
                        .HasColumnType("integer")
                        .HasColumnName("database_connection_id");

                    b.Property<string>("GuardDescription")
                        .HasColumnType("text")
                        .HasColumnName("guard_description");

                    b.Property<string>("GuardName")
                        .HasColumnType("text")
                        .HasColumnName("guard_name");

                    b.Property<int>("GuardState")
                        .HasColumnType("integer")
                        .HasColumnName("guard_state");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastEditedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_date");

                    b.Property<DateTimeOffset?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<bool>("NotifyOnClear")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_clear");

                    b.Property<bool>("NotifyOnError")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_error");

                    b.Property<bool>("NotifyOnTrigger")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_trigger");

                    b.Property<double>("RunPeriodInMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("run_period_in_minutes");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("integer")
                        .HasColumnName("total_errors");

                    b.Property<int>("TotalTriggers")
                        .HasColumnType("integer")
                        .HasColumnName("total_triggers");

                    b.Property<int>("TriggerOperator")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_operator");

                    b.Property<string>("TriggerQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_query");

                    b.Property<int>("TriggerValue")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_value");

                    b.HasKey("Id")
                        .HasName("pk_guards");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_guards_created_by_user_id");

                    b.HasIndex("DatabaseConnectionId")
                        .HasDatabaseName("ix_guards_database_connection_id");

                    b.ToTable("guards", (string)null);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardChangeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DatabaseConnectionEndPoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_connection_end_point");

                    b.Property<int>("DatabaseConnectionEngine")
                        .HasColumnType("integer")
                        .HasColumnName("database_connection_engine");

                    b.Property<int?>("DatabaseConnectionId")
                        .HasColumnType("integer")
                        .HasColumnName("database_connection_id");

                    b.Property<string>("DatabaseConnectionUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_connection_username");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<int?>("GuardId")
                        .HasColumnType("integer")
                        .HasColumnName("guard_id");

                    b.Property<int>("GuardOperator")
                        .HasColumnType("integer")
                        .HasColumnName("guard_operator");

                    b.Property<string>("GuardQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guard_query");

                    b.Property<int>("GuardState")
                        .HasColumnType("integer")
                        .HasColumnName("guard_state");

                    b.Property<int>("GuardValue")
                        .HasColumnType("integer")
                        .HasColumnName("guard_value");

                    b.Property<int>("PreviousGuardState")
                        .HasColumnType("integer")
                        .HasColumnName("previous_guard_state");

                    b.Property<int?>("ResultValue")
                        .HasColumnType("integer")
                        .HasColumnName("result_value");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_guard_change_transactions");

                    b.HasIndex("DatabaseConnectionId")
                        .HasDatabaseName("ix_guard_change_transactions_database_connection_id");

                    b.HasIndex("GuardId")
                        .HasDatabaseName("ix_guard_change_transactions_guard_id");

                    b.ToTable("guard_change_transactions", (string)null);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int>("GuardId")
                        .HasColumnType("integer")
                        .HasColumnName("guard_id");

                    b.Property<DateTimeOffset>("LastEdited")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited");

                    b.Property<int>("NotificationProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_provider_id");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.HasKey("Id")
                        .HasName("pk_guard_notifications");

                    b.HasIndex("GuardId")
                        .HasDatabaseName("ix_guard_notifications_guard_id");

                    b.HasIndex("NotificationProviderId")
                        .HasDatabaseName("ix_guard_notifications_notification_provider_id");

                    b.ToTable("guard_notifications", (string)null);

                    b.HasDiscriminator<int>("NotificationType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.NotificationTransactions.NotificationTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuardChangeTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("guard_change_transaction_id");

                    b.Property<int?>("GuardId")
                        .HasColumnType("integer")
                        .HasColumnName("guard_id");

                    b.Property<int?>("GuardNotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("guard_notification_id");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_notification_transactions");

                    b.HasIndex("GuardChangeTransactionId")
                        .HasDatabaseName("ix_notification_transactions_guard_change_transaction_id");

                    b.HasIndex("GuardId")
                        .HasDatabaseName("ix_notification_transactions_guard_id");

                    b.HasIndex("GuardNotificationId")
                        .HasDatabaseName("ix_notification_transactions_guard_notification_id");

                    b.ToTable("notification_transactions", (string)null);

                    b.HasDiscriminator<int>("NotificationType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("LastEditedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_date");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer")
                        .HasColumnName("provider_type");

                    b.HasKey("Id")
                        .HasName("pk_notification_providers");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_notification_providers_created_by_user_id");

                    b.ToTable("notification_providers", (string)null);

                    b.HasDiscriminator<int>("ProviderType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastEdited")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_asp_net_users_created_by_user_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Views.GuardView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CountColumn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("count_column");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DatabaseConnectionId")
                        .HasColumnType("integer")
                        .HasColumnName("database_connection_id");

                    b.Property<int>("DatabaseEngine")
                        .HasColumnType("integer")
                        .HasColumnName("database_engine");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_point");

                    b.Property<string>("GuardName")
                        .HasColumnType("text")
                        .HasColumnName("guard_name");

                    b.Property<int>("GuardState")
                        .HasColumnType("integer")
                        .HasColumnName("guard_state");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<double>("RunPeriodInMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("run_period_in_minutes");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("integer")
                        .HasColumnName("total_errors");

                    b.Property<int>("TotalTriggers")
                        .HasColumnType("integer")
                        .HasColumnName("total_triggers");

                    b.Property<int>("TriggerOperator")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_operator");

                    b.Property<int>("TriggerValue")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_value");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_guard_view");

                    b.ToTable((string)null);

                    b.ToView("guard_view", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardNotifications.EmailNotification", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification");

                    b.PrimitiveCollection<List<string>>("BCCEmails")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("bcc_emails");

                    b.PrimitiveCollection<List<string>>("CCEmails")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cc_emails");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_body");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_subject");

                    b.PrimitiveCollection<List<string>>("ToEmails")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("to_emails");

                    b.ToTable("guard_notifications", (string)null);

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardNotifications.TextNotification", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification");

                    b.PrimitiveCollection<List<string>>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phone_numbers");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_message");

                    b.ToTable("guard_notifications", (string)null);

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.NotificationTransactions.EmailNotificationTransaction", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.NotificationTransactions.NotificationTransaction");

                    b.Property<string>("BCCEmails")
                        .HasColumnType("text")
                        .HasColumnName("bcc_emails");

                    b.Property<string>("CCEmails")
                        .HasColumnType("text")
                        .HasColumnName("cc_emails");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_body");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_subject");

                    b.Property<string>("ToEmails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_emails");

                    b.ToTable("notification_transactions", (string)null);

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.NotificationTransactions.TextNotificationTransaction", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.NotificationTransactions.NotificationTransaction");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_numbers");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_message");

                    b.ToTable("notification_transactions", (string)null);

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.ServiceProviders.EmailProvider", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("SMTPServer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("smtp_server");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.ToTable("notification_providers", (string)null);

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.ServiceProviders.TextProvider", b =>
                {
                    b.HasBaseType("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.ToTable("notification_providers", (string)null);

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.DatabaseConnection", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", "CreatedByUser")
                        .WithMany("DatabaseConnections")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_database_connections_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.Guard", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", "CreatedByUser")
                        .WithMany("Guards")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_guards_users_created_by_user_id");

                    b.HasOne("DBGuardAPI.Data.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany("Guards")
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guards_database_connections_database_connection_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DatabaseConnection");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardChangeTransaction", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany("GuardChangeTransactions")
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_guard_change_transactions_database_connections_database_con");

                    b.HasOne("DBGuardAPI.Data.Models.Guard", "Guard")
                        .WithMany("GuardChangeTransactions")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_guard_change_transactions_guards_guard_id");

                    b.Navigation("DatabaseConnection");

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.Guard", "Guard")
                        .WithMany("GuardNotifications")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guard_notifications_guards_guard_id");

                    b.HasOne("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider", "NotificationProvider")
                        .WithMany("GuardNotifications")
                        .HasForeignKey("NotificationProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guard_notifications_notification_providers_notification_pro");

                    b.Navigation("Guard");

                    b.Navigation("NotificationProvider");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.NotificationTransactions.NotificationTransaction", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.GuardChangeTransaction", "GuardChangeTransaction")
                        .WithMany("NotificationTransactions")
                        .HasForeignKey("GuardChangeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_transactions_guard_change_transactions_guard_c");

                    b.HasOne("DBGuardAPI.Data.Models.Guard", "Guard")
                        .WithMany("NotificationTransactions")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_transactions_guards_guard_id");

                    b.HasOne("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification", "GuardNotification")
                        .WithMany("NotificationTransactions")
                        .HasForeignKey("GuardNotificationId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("fk_notification_transactions_guard_notifications_guard_notific");

                    b.Navigation("Guard");

                    b.Navigation("GuardChangeTransaction");

                    b.Navigation("GuardNotification");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", "CreatedByUser")
                        .WithMany("NotificationProviders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notification_providers_asp_net_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.User", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asp_net_users_asp_net_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DBGuardAPI.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DBGuardAPI.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.DatabaseConnection", b =>
                {
                    b.Navigation("GuardChangeTransactions");

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.Guard", b =>
                {
                    b.Navigation("GuardChangeTransactions");

                    b.Navigation("GuardNotifications");

                    b.Navigation("NotificationTransactions");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardChangeTransaction", b =>
                {
                    b.Navigation("NotificationTransactions");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.GuardNotifications.GuardNotification", b =>
                {
                    b.Navigation("NotificationTransactions");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.ServiceProviders.NotificationProvider", b =>
                {
                    b.Navigation("GuardNotifications");
                });

            modelBuilder.Entity("DBGuardAPI.Data.Models.User", b =>
                {
                    b.Navigation("CreatedUsers");

                    b.Navigation("DatabaseConnections");

                    b.Navigation("Guards");

                    b.Navigation("NotificationProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
